/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecentlyViewedRouteImport } from './routes/recently-viewed'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerInquiriesRouteImport } from './routes/seller.inquiries'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as SellerPropertiesIndexRouteImport } from './routes/seller.properties.index'
import { Route as SellerPropertiesCreateRouteImport } from './routes/seller.properties.create'
import { Route as SellerPropertiesIdEditRouteImport } from './routes/seller.properties.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentlyViewedRoute = RecentlyViewedRouteImport.update({
  id: '/recently-viewed',
  path: '/recently-viewed',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerInquiriesRoute = SellerInquiriesRouteImport.update({
  id: '/seller/inquiries',
  path: '/seller/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/seller/profile',
  path: '/seller/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPropertiesIndexRoute = SellerPropertiesIndexRouteImport.update({
  id: '/seller/properties/',
  path: '/seller/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPropertiesCreateRoute = SellerPropertiesCreateRouteImport.update({
  id: '/seller/properties/create',
  path: '/seller/properties/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPropertiesIdEditRoute = SellerPropertiesIdEditRouteImport.update({
  id: '/seller/properties/$id/edit',
  path: '/seller/properties/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inquiries': typeof SellerInquiriesRoute
  '/seller/profile': typeof SellerProfileRoute
  '/properties/': typeof PropertiesIndexRoute
  '/seller/properties/create': typeof SellerPropertiesCreateRoute
  '/seller/properties/': typeof SellerPropertiesIndexRoute
  '/seller/properties/$id/edit': typeof SellerPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inquiries': typeof SellerInquiriesRoute
  '/seller/profile': typeof SellerProfileRoute
  '/properties': typeof PropertiesIndexRoute
  '/seller/properties/create': typeof SellerPropertiesCreateRoute
  '/seller/properties': typeof SellerPropertiesIndexRoute
  '/seller/properties/$id/edit': typeof SellerPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/category/$slug': typeof CategorySlugRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/seller/$id': typeof SellerIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inquiries': typeof SellerInquiriesRoute
  '/seller/profile': typeof SellerProfileRoute
  '/properties/': typeof PropertiesIndexRoute
  '/seller/properties/create': typeof SellerPropertiesCreateRoute
  '/seller/properties/': typeof SellerPropertiesIndexRoute
  '/seller/properties/$id/edit': typeof SellerPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/recently-viewed'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/category/$slug'
    | '/properties/$id'
    | '/seller/$id'
    | '/seller/dashboard'
    | '/seller/inquiries'
    | '/seller/profile'
    | '/properties/'
    | '/seller/properties/create'
    | '/seller/properties/'
    | '/seller/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/recently-viewed'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/category/$slug'
    | '/properties/$id'
    | '/seller/$id'
    | '/seller/dashboard'
    | '/seller/inquiries'
    | '/seller/profile'
    | '/properties'
    | '/seller/properties/create'
    | '/seller/properties'
    | '/seller/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/recently-viewed'
    | '/register'
    | '/reset-password'
    | '/saved'
    | '/category/$slug'
    | '/properties/$id'
    | '/seller/$id'
    | '/seller/dashboard'
    | '/seller/inquiries'
    | '/seller/profile'
    | '/properties/'
    | '/seller/properties/create'
    | '/seller/properties/'
    | '/seller/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecentlyViewedRoute: typeof RecentlyViewedRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  SellerIdRoute: typeof SellerIdRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerInquiriesRoute: typeof SellerInquiriesRoute
  SellerProfileRoute: typeof SellerProfileRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  SellerPropertiesCreateRoute: typeof SellerPropertiesCreateRoute
  SellerPropertiesIndexRoute: typeof SellerPropertiesIndexRoute
  SellerPropertiesIdEditRoute: typeof SellerPropertiesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recently-viewed': {
      id: '/recently-viewed'
      path: '/recently-viewed'
      fullPath: '/recently-viewed'
      preLoaderRoute: typeof RecentlyViewedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/inquiries': {
      id: '/seller/inquiries'
      path: '/seller/inquiries'
      fullPath: '/seller/inquiries'
      preLoaderRoute: typeof SellerInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/seller/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/properties/': {
      id: '/seller/properties/'
      path: '/seller/properties'
      fullPath: '/seller/properties/'
      preLoaderRoute: typeof SellerPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/properties/create': {
      id: '/seller/properties/create'
      path: '/seller/properties/create'
      fullPath: '/seller/properties/create'
      preLoaderRoute: typeof SellerPropertiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/properties/$id/edit': {
      id: '/seller/properties/$id/edit'
      path: '/seller/properties/$id/edit'
      fullPath: '/seller/properties/$id/edit'
      preLoaderRoute: typeof SellerPropertiesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecentlyViewedRoute: RecentlyViewedRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  CategorySlugRoute: CategorySlugRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  SellerIdRoute: SellerIdRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerInquiriesRoute: SellerInquiriesRoute,
  SellerProfileRoute: SellerProfileRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  SellerPropertiesCreateRoute: SellerPropertiesCreateRoute,
  SellerPropertiesIndexRoute: SellerPropertiesIndexRoute,
  SellerPropertiesIdEditRoute: SellerPropertiesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
